{% set version = "0.0.1" %}

package:
  name: r-w4mrutils
  version: "{{ version }}"

source:
  url: https://github.com/workflow4metabolomics/W4MRUtils/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b6c2f7b3aae2bb88a8f27db40596a76bcd5f84b2d1324f8147787b070087c037

build:
  noarch: generic
  number: 0

requirements:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('W4MRUtils')"           # [not win]
    - "\"%R%\" -e \"library('W4MRUtils')\""  # [win]

about:
  home: https://github.com/workflow4metabolomics/W4MRUtils
  license: AGPL-3.0-or-later
  license_file: LICENSE.md
  summary: 'Some utils tools for W4M'
  description: |
    Provides a set of utility function to prevent the spread of
    utilities script in W4M scripts, and centralize them in a package.
    Some are meant to be replaced by real packages in a near future, like
    the parse_args function: it is here only to prepare the ground for
    more global changes in W4M scripts and tools.
  dev_url: https://github.com/workflow4metabolomics/W4MRUtils
  doc_url: https://github.com/workflow4metabolomics/W4MRUtils
  doc_source_url: https://github.com/workflow4metabolomics/W4MRUtils/blob/v{{ version }}/README.md

extra:
  recipe-maintainers:
    - Lain-inrae
    - conda-forge/r
